MODEL:
  PRETRAIN_CHOICE: 'latest'
  PRETRAIN_PATH: '/root/autodl-nas/Re-ID/Re-ID-AGW/checkloints/cuhk03/cuhk03_AGW.pth'
  CENTER_LOSS: 'on'
  CENTER_FEAT_DIM: 2048
  NAME: 'resnet50_nl'
  WEIGHT_REGULARIZED_TRIPLET: 'on'
  GENERALIZED_MEAN_POOL: 'on'

INPUT:
  IMG_SIZE: [256, 128]
  PROB: 0.5
  RE_PROB: 0.5
  PADDING: 10

DATASETS:
  NAMES: ('cuhk03')
  QA_LABELS: '/root/autodl-nas/Re-ID/quality_pseudo_lables/cuhk03_trainset_pseudo-labels.txt'

DATALOADER:
  PK_SAMPLER: 'on'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'Adam'
  MAX_EPOCHS: 200
  BASE_LR: 0.0000035

  CENTER_LR: 0.5
  CENTER_LOSS_WEIGHT: 0.0005

  WEIGHT_DECAY: 0.0005
  IMS_PER_BATCH: 64

  STEPS: [50, 90]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 10
  WARMUP_METHOD: 'linear'

  CHECKPOINT_PERIOD: 5
  LOG_PERIOD: 20
  EVAL_PERIOD: 1

TEST:
  EVALUATE_ONLY: 'off'   # 'on' is for test only
  IMS_PER_BATCH: 256
  RE_RANKING: 'off'
  WEIGHT: "./xxxx/PATH"   # the path of checkpoint you want to test
  FEAT_NORM: 'on'
  PARTIAL_REID: 'off'

OUTPUT_DIR: "/root/Re-ID-AGW/QSD/log"


